---
title: "Spatial scaling of extinction rates, and it's link to biological processes"
author: "Petr Keil, Vojtech Bartak, Francois Leroy"
date: "2023-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Settings and Libraries

```{r, warning = FALSE, message = FALSE}
library(mobsim) # simulating point pattern communities
library(manipulate) # sliders and interactive plotting
library(randomForest) # random forest

# graphics
library(tidyverse)
library(gridExtra) # multiple ggplots in a figure
library(latex2exp) # for math symbols in figures

# parallel computation
library(foreach)
library(doParallel)

# our own functions
source("extinctions_functions.r")

# setting the random seed
set.seed(12345)
```

# Histograms illustrating different SADs

```{r, fig.width=10}
dat <- SAD.prob.mass(1000, 100, cv_abund.vect = c(10))

SAD10 <- ggplot(data = dat, aes(x=N, y = PM)) +
          geom_point() +
          geom_line() +
          theme_classic() + 
          ylim(0, 0.2) + ylab("Probablity mass") + 
          xlab("Species abundance (# of individuals)") +
          labs(title= "(a)") 
          
SAD10

N = 100
S = 10
cv.abund = 1
sigma = 0.1
alpha = 0.9
beta = -1
side.divisions = c(2,4,8,16)
set.seed(1234)

eff1 <- data.frame(N = seq(1,40), 
                   P.death = effect.f(alpha, beta, N = seq(1,40), plot=FALSE))
eff1.plot <- ggplot(data = eff1, aes(x = N, y = P.death)) + 
        geom_point() +
        geom_line() +
        ylim(0,1) + 
        ylab(expression(P[death])) +
        theme_classic() + 
        xlab("Species abundance (# of individuals)") +
        labs(title= "(b)") 

  com <- sim_thomas_community(n_sim  = N,
                              s_pool = S,
                              sad_coef = list(cv_abund = cv.abund),
                              mother_points = 1,
                              sigma  = sigma)

  # Species-Abundance Distribution - SAD
  SAD <- data.frame(table(com$census$species))
  names(SAD) <- c("species", "N.tot")
  SAD$species <- as.character(SAD$species)
  census <- left_join(com$census, SAD, by="species")
  
  # re-scale P.minus
  P.minus.vect <- effect.f(alpha, beta, N = census$N.tot, plot = FALSE)
  
  # sample individuals that will be killed
  deaths <- rbinom(n = length(P.minus.vect), size = 1, prob = P.minus.vect)
  dead.coords <- com$census[deaths == 1, ]
  
  ef <- effect.f(alpha, beta, plot = TRUE)
  
  deltas <- com.extinction(com, 
                           side.divisions, 
                           alpha = alpha, 
                           beta = beta,
                           plot.res = TRUE)


# ------------------------------------------------------------------------------  
# plot just the points
  ggplot(data = com$census, aes(x = x, y = y)) +
      geom_point(aes(colour = species)) +
    theme_minimal() + 
     #geom_point(data = dead.coords, shape = 4, size = 2.5) +
        coord_fixed(ratio = 1) +
        scale_x_continuous(breaks = seq(0, 1, by = 1/grains[i])) + 
        scale_y_continuous(breaks = seq(0, 1, by = 1/grains[i])) + 
        theme(axis.text.x=element_blank(),
              legend.position = "none",
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              axis.text.y=element_blank(),
              axis.title.x=element_blank(), axis.title.y=element_blank()) +
        labs(title= my.labs[i]) 
  
  
  
# ------------------------------------------------------------------------------  
  figs <- list()
  grains <- c(16,8,4,2)
  my.labs <- c("(c)"," ", " ", " ")
  for(i in 1:length(grains))
  {
    figs[[i]] <-  ggplot(data = com$census, aes(x = x, y = y)) +
      geom_point(aes(colour = species)) + 
      geom_point(data = dead.coords, shape = 4, size = 2.5) +
      theme_minimal() + 
        coord_fixed(ratio = 1) +
        scale_x_continuous(breaks = seq(0, 1, by = 1/grains[i])) + 
        scale_y_continuous(breaks = seq(0, 1, by = 1/grains[i])) + 
        theme(axis.text.x=element_blank(),
              legend.position = "none",
              axis.text.y=element_blank(),
              panel.grid.major = element_line(color = "darkgrey"),
              panel.grid.minor = element_blank(),
              axis.title.x=element_blank(), axis.title.y=element_blank()) +
        labs(title= my.labs[i]) 
  }
  
  grid.arrange(figs[[1]], figs[[2]], figs[[3]], figs[[4]], nrow = 1)

    
 ExAR<- ggplot(data = deltas, aes(x = A, y = E.x)) + 
    geom_point() +
    scale_x_continuous(trans='log10') +
    geom_smooth(method = lm, se = FALSE, colour = "black", size = 0.5) +
    ylim(c(0,1.5)) + 
    theme_classic() +
    xlab("Area") +
    ylab("E") +
    labs(title= "(d)")

   
 PxAR <- ggplot(data = deltas, aes(x = A, y = P.x)) + 
    geom_point() +
    scale_x_continuous(trans='log10') +
    geom_smooth(method = lm, se = FALSE, colour = "black", size = 0.5) +
    ylim(c(0,1)) + 
    theme_classic() +
    xlab("Area") +
    ylab("Px") +
    labs(title= "(e)") 

  
  
  lay.mat <- matrix(c(1,1,2,2,
                      3,4,5,6,
                      7,7,8,8), 
                    nrow = 3, ncol=4, byrow=TRUE)
  
    grid.arrange(SAD10, eff1.plot,
               figs[[1]], figs[[2]], figs[[3]], figs[[4]],
               ExAR, PxAR, layout_matrix = lay.mat)
  
pdf("JC.pdf")  
  grid.arrange(SAD10, eff1.plot,
               figs[[1]], figs[[2]], figs[[3]], figs[[4]],
               ExAR, PxAR, layout_matrix = lay.mat)
dev.off()
```


# Hypothesis 3

```{r}

  A = 1:100
  z=0.28
  exz = -0.1
  c=3
  S = c*A^z
  
  # CURVE 1 - shallow power law
  P_E1 = (c*A^exz)/max(c*A^exz)*0.5
  E1 = S*P_E1

  # CURVE 2
  exz2 = -0.3
  P_E2 = (2*(1-A/max(A)))/max(2*(1-A/max(A)))*0.2 + 0.3 
  P_E2 = 0.5 - 0.003*A; plot(A, P_E2)
  E2 = S*P_E2
  
  # CURVE 3
  P_E3 = (10^(A^-0.3))/max(10^(A^-0.3))*0.5
  E3 = S*P_E3
  
  dat <- data.frame(A = rep(A, times = 3), 
                    S = rep(S, times = 3),
                    Px = c(P_E1, P_E2, P_E3),
                    Ex = c(E1, E2, E3),
                    scenario = rep(c("i","ii","iii"), each = length(A)))
  
  ggplot(data = dat, aes(x = A, y = S)) + 
    geom_line(aes(linetype = scenario)) + 
    labs(title = "(a) SAR") +
    scale_x_continuous(trans='log10') +
    scale_y_continuous(trans='log10') +
    theme(legend.title=element_blank()) +
    theme_classic()  
  
  ggplot(data = dat, aes(x = A, y = Px)) + 
    geom_line(aes(linetype = scenario)) + 
    scale_x_continuous(trans='log10') +
    labs(title = "(b) PxAR") +
    theme(legend.title=element_blank()) +
    theme_classic()  
  
  ggplot(data = dat, aes(x = A, y = Ex)) + 
    geom_line(aes(linetype = scenario)) + 
    scale_x_continuous(trans='log10') +
    labs(title = "(c) ExAR") +
    theme(legend.title=element_blank()) +
    theme_classic()  
  
  
```
  
  
```{r}  
pdf("Figure_SAR.pdf", width=8, height=2.7)  
 par(mfrow=c(1,3), mai=c(0.7,0.7,0.3,0.1))
  
 
 
 
 ## PLOT 1
 plot(A, S, type="l", frame=FALSE, lwd=2, las=1, 
       #ylab=expression(paste(log[10], italic(" S"))),
       ylab=expression(italic(" S")),
       xlab=expression(italic(" A")),
       main="SAR (given)", 
       font.main = 1)  
 mtext("a", side=3, adj=-0.2, padj=-0.5, font=2)

 ## PLOT 2
 plot(A, P_E1, type="l", frame=FALSE, ylim=c(0,0.6), las=1,
      ylab=expression(italic("P"[X])),
      xlab=expression(italic("A")), lwd=2, lty=1, col=mypal[1],
      main="PxAR (given)", 
      font.main = 1) 
 lines(A, P_E2, col=mypal[2], lwd=2, lty=2)
 lines(A, P_E3, col=mypal[3], lwd=2, lty=4)
 mtext("b", side=3, adj=-0.2, padj=-0.5, font=2)
 
 
 ## PLOT 3
 plot(A, E1, type="l", ylab=expression(italic("N"[X])), 
                       xlab=expression(italic("A")),
      frame=FALSE, ylim=c(0,4), lwd=2, 
      col=mypal[1], las=1, lty=1,
      main=expression(paste("NxAR = ", SAR %*% PxAR)), 
      font.main = 1) 
 lines(A, E2, col=mypal[2], lwd=2, lty=2)
 lines(A, E3, col=mypal[3], lwd=2, lty=4)
 mtext("c", side=3, adj=-0.2, padj=-0.5, font=2)

dev.off()

# ------------------------------------------------------------------------------

```




